### ISSUE TITLE
Do not run under Graylog 2.2.2

### ISSUE THREAD

**Issue by keitopso** [billmurrin/graylog-plugin-quickvaluesplus-widget#2]
Hi, 

thanks for this QuickValues-Plugin. 

But this Graylog plugin do not run under Graylog-Server 2.2.2. 

Best regards

**Comment by billmurrin** [comment]
Hi @keitopso, I'm running this plugin under 2.2.2 right now. 

Would you be able to tell if you have any errors in your Graylog server log or web browser debugger?

Have you cleared your browser cache or forced refresh (Ctrl + F5) to reload all of the files for the web interface? If not, I would definitely try that.

Lastly, can you please provide your OS and browser version so I can try to replicate the issue.

Thanks.

**Comment by billmurrin** [comment]
I downloaded the 2.2.2 ova file, booted it, added the plugins, restarted it and then used the plugin with no issues. If you do not have any additional input or information, I will close out this issue.

**Comment by keitopso** [comment]
Hi @billmurrin, 

thanks for you reply. 

There are no erros in Graylog server log.  In the web browser debugger I do not see any information about quickvalues plugin.

**Comment by billmurrin** [comment]
Were you able to get it to work @keitopso?

If not, can you give me a screenshot of what your screen looks like when you expand a field in the sidebar?

Also, did you try clearing your browser cache and forcing a refresh of the web interface?

**Comment by keitopso** [comment]
It do not run in setup. I cleared the Browser cache and delete all other graylog plugins with ui-features. After this I restarted the graylog-server.  

![grafik](https://cloud.githubusercontent.com/assets/15252875/24238119/6761b5a8-0fa9-11e7-8aae-78fe166bbdf4.png)

**Comment by billmurrin** [comment]
Did you adjust the permissions on the plugin? It may not have loaded, ensure that Graylog has permissions to read the plugin, might require a 644 type of permission.

If you restart Graylog and tail the server.log file, do you see the plugin getting loaded? The plugins getting loaded should be near the top of the log output upon restart.
