### ISSUE TITLE
Plugin not visible

### ISSUE THREAD

**Issue by tomuk5** [billmurrin/graylog-plugin-quickvaluesplus-widget#29]
packages installed below:
ii  graylog-2.3-repository  1-5  Package to install Graylog 2.3 GPG key and repository
ii  graylog-plugin-aggregates   2.0.0  Graylog graylog-plugin-aggregates plugin.
ii  graylog-plugin-quickvaluesplus-widget 3.0.1  Graylog graylog-plugin-quickvaluesplus-widget plugin.
ii  graylog-server     2.3.1-1   Graylog server

plugin is not visible in configuration dialog or any stream's, no errors shown in /var/log/graylog-server/* 

browser cache cleared but still not working

**Comment by billmurrin** [comment]
Hi @tomuk5, please check the permissions on the plugin on the Graylog side. 

Most times I've seen where the plugin wasn't loaded, it has been permissions related, i.e. the Graylog server cannot access, therefore, read the plugin.

**Comment by tomuk5** [comment]
Hi Bill, iv checked the permissions match the other plugins I’m using and in the graylog.log file it shows the plugin as being loaded but there is no visual effect of it being loaded in the gui.
It’s listed in the gui as loaded on each node as a plugin as well and displays the correct version too

Many thanks

Tom

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billmurrin** [comment]
Tom, 

Can you load the debug version of the plugin and monitor your developer console output to see if it is outputting anything? Even when the plugin hasn't been added, the component should be mounting inside of React. 

Just replace the normal version with this and restart Graylog.
https://www.dropbox.com/s/ncsyci2rfapo4gf/graylog-plugin-quickvaluesplus-widget-3.0.1.jar?dl=0

If you are looking at the Dev tools in your browser, under Javascript files, do you see the quickvalues javascript file being loaded?

Also, what OS and browser are you using?

Thanks, hopefully, we'll get this figured out soon.

-Bill

**Comment by billmurrin** [comment]
Tom,

Any update on loading the Debug version of the plugin?

**Comment by billmurrin** [comment]
No response. Closing issue.
