### ISSUE TITLE
Quick Values in Dashboard keep changing colors

### ISSUE THREAD

**Issue by merasil** [billmurrin/graylog-plugin-quickvaluesplus-widget#31]
There seems to be an issue with refreshing the quick values plus widgets in a dashboard. Everytime the Dashboard refreshs itself the Widget seems to be build up the pie chart again and changes the color of the values.

**Comment by billmurrin** [comment]
Thanks for the report. Fixed in https://github.com/billmurrin/graylog-plugin-quickvaluesplus-widget/commit/eb708fbe3aa3f17616e3b8c16d902d76a337433d. Fix will be released as part of release 3.1.0.
