### ISSUE TITLE
Plugin Loaded but not usable/no config

### ISSUE THREAD

**Issue by jalogisch** [billmurrin/graylog-plugin-quickvaluesplus-widget#35]
I'm using a fresh installation of Graylog 2.3.2 on Ubuntu 16.4. and install the .deb version of the plugin version 3.0.1.

![plugin_loaded](https://user-images.githubusercontent.com/404238/33717645-0f6ad180-db5b-11e7-9915-4219580600d6.png)

But no configuration is located on the *System > Configuration* page. How can I provide you additional Information that you can debug that?

**Comment by billmurrin** [comment]
Hi @jalogisch - I'm having issues viewing the image right now, but I'll look into it.

I'll have to research the .deb plugin itself. I'll be honest and say I haven't done much testing on the rpm or deb plugins. Does the plugin work OK if you use the .jar version of the plugin? If it works OK with the JAR version, that will at least point me in the right direction. Sorry for the inconvenience.

**Comment by billmurrin** [comment]
@jalogisch Do you have any errors in the config? Can you please see issue #33 and see if you have a similar output. Thanks.

**Comment by jalogisch** [comment]
Hej @billmurrin 

it took me some time to return to this. Even with the .jar Version I'm facing the same issue. If you like, I can export that VM so you are able to look at. 

As this is our Graylog Training VM it does not contain any sensitiv data and is 'small'. Let me know what works best for you.

**Comment by billmurrin** [comment]
Thanks @jalogisch. I'm glad it is at least working with the .jar release. Does it look like the .deb is still experiencing an issue or do you think it was pretty much related to the browser cache?

**Comment by jalogisch** [comment]
I tried a _full page reload_ several times with the .deb version to ensure that this works.

If you like to investigate, I can share the VM.

**Comment by billmurrin** [comment]
Sure, I'll take a look at the VM. Thanks.

**Comment by jalogisch** [comment]
Send you a Mail with details. thnx

**Comment by billmurrin** [comment]
@jalogisch - I observed that the size when installed from the .deb is only 18kb instead of the 3.32MB it should be. The java code is present but all of the javascript is missing.

![JAR and Deb Package Comparison](https://i.imgur.com/qk6qjhg.png)

I'll work on getting it fixed.

**Comment by billmurrin** [comment]
@jalogisch - Please update to v3.0.3. The .deb should be working now.
